name: Deploy Eleventy site to GitHub Pages

on:
  push:
    branches: [ main ]   # Or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # This step runs your full build, generating Tailwind CSS and HTML
      - name: Build Eleventy site with Tailwind
        run: npm run build

      # Ensure .nojekyll is present (avoids GitHub Pages processing)
      - name: Add .nojekyll
        run: cp .nojekyll _site/.nojekyll || touch _site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
